### ISSUE TITLE
To what does LICENSE.CSIRO apply

### ISSUE THREAD

**Issue by QuLogic** [pyoceans/python-seawater#16]
IANAL, but the restrictions in 2.1 appear enough to make this license non-free, which would make distros very wary about taking on this package. So it would be nice to clarify what exact files are covered by this license and whether or not they can be removed?

**Comment by QuLogic** [comment]
Section 2.2 also looks a bit troubling, especially 2.2(a) which I could almost interpret as covering translations as well.

**Comment by ocefpaf** [comment]
Closing his as we removed this dependency on folium and that license applies only to the matlab code in the tests folder.
