### ISSUE TITLE
Error of units in the documentation of eos80.dens(s, t, p)

### ISSUE THREAD

**Issue by Julien-Gustin** [pyoceans/python-seawater#17]
In the documentation I see that you consider the unit of the density as [kg m :sup:`3`]. However according to https://unesdoc.unesco.org/ark:/48223/pf0000059832 a density corresponds to [kg m :sup:`-3`].

**Comment by ocefpaf** [comment]
This package is deprecated in lieu of TESO-10. You should really be using that one instead. See https://github.com/TEOS-10/GSW-Python. Closing this b/c the only reason this package exists is for legacy purposes.
