### ISSUE TITLE
Brünt-Väisälä Frequency at a given depth

### ISSUE THREAD

**Issue by arnaldorusso** [pyoceans/python-seawater#6]
Hi,

How should be computed the Brünt-Väisälä Frequency at a given depth?
For example, I want to compute the Brünt-Väisälä Frequency directly below the upper mixed layer depth.

`bfrq`[0] is returned for every recorded depth?? I could slice this output with desired depth index?

Thanks

**Comment by ocefpaf** [comment]
As the docs says:
```python
"""
    Calculates Brünt-Väisälä Frequency squared (N :sup:`2`) at the mid depths...
"""
```

Bare in mind that it returns the mid depths.

```python
"""
    n2 : array_like
           Brünt-Väisälä Frequency squared (M-1xN)  [rad s :sup:`-2`]
    q : array_like
           planetary potential vorticity (M-1xN)  [ m s :sup:`-1`]
    p_ave : array_like
            mid pressure between P grid (M-1xN) [db]
"""
```

Use `p_ave` to get the point closest to your desired depth.  Or, if the resolution permits, interpolate `n2` to your desired depth.
